=== MWJones96/medly-backend-take-home-task/curriculum_data/aqaGCSEBio_exams_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "board_title": {
        "type": "string"
      },
      "qualification": {
        "type": "string"
      },
      "subject_title": {
        "type": "string"
      },
      "subject_id": {
        "type": "string"
      },
      "type": {
        "type": "string"
      },
      "series": {
        "type": "string"
      },
      "papers": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "paper_id": {
              "type": "string"
            },
            "tier": {
              "type": "string"
            },
            "paper": {
              "type": "string"
            },
            "questions": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "question_number": {
                    "type": "integer"
                  },
                  "question_stem": {
                    "type": "string"
                  },
                  "question_stem_diagram": {
                    "anyOf": [
                      {
                        "type": [
                          "null",
                          "string"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "required": {
                            "type": "boolean"
                          },
                          "items": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "description": {
                                  "type": "string"
                                },
                                "method": {
                                  "type": "string"
                                },
                                "attempts": {
                                  "type": "array",
                                  "items": {
                                    "type": "object",
                                    "properties": {
                                      "attempt_number": {
                                        "type": "integer"
                                      },
                                      "latex_code": {
                                        "type": "null"
                                      },
                                      "success": {
                                        "type": "boolean"
                                      },
                                      "svg": {
                                        "type": "null"
                                      },
                                      "png_path": {
                                        "type": "string"
                                      },
                                      "error_message": {
                                        "type": "null"
                                      },
                                      "retry_count": {
                                        "type": "integer"
                                      },
                                      "missing_content": {
                                        "type": "array"
                                      },
                                      "llm_rank": {
                                        "type": "integer"
                                      },
                                      "llm_feedback": {
                                        "type": "null"
                                      },
                                      "requires_intervention": {
                                        "type": "null"
                                      }
                                    },
                                    "required": [
                                      "attempt_number",
                                      "error_message",
                                      "latex_code",
                                      "llm_feedback",
                                      "llm_rank",
                                      "missing_content",
                                      "png_path",
                                      "requires_intervention",
                                      "retry_count",
                                      "success",
                                      "svg"
                                    ]
                                  }
                                },
                                "final": {
                                  "type": "object",
                                  "properties": {
                                    "png_path": {
                                      "type": "string"
                                    }
                                  },
                                  "required": [
                                    "png_path"
                                  ]
                                }
                              },
                              "required": [
                                "attempts",
                                "description",
                                "final",
                                "method"
                              ]
                            }
                          }
                        },
                        "required": [
                          "items",
                          "required"
                        ]
                      }
                    ]
                  },
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "question_part": {
                          "type": "integer"
                        },
                        "question_type": {
                          "type": "string"
                        },
                        "question_text": {
                          "type": "string"
                        },
                        "markmax": {
                          "type": "integer"
                        },
                        "markscheme": {
                          "type": "string"
                        },
                        "difficulty": {
                          "type": "integer"
                        },
                        "lessonIDs": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "questionID": {
                          "type": "string"
                        },
                        "options": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "correct_answer_index": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "lessonIDs",
                        "markmax",
                        "markscheme",
                        "questionID",
                        "question_part",
                        "question_text",
                        "question_type"
                      ]
                    }
                  },
                  "validation_comment": {
                    "type": "string"
                  },
                  "validation_reason": {
                    "type": "string"
                  },
                  "question_id": {
                    "type": "string"
                  }
                },
                "required": [
                  "items",
                  "question_id",
                  "question_number",
                  "question_stem",
                  "question_stem_diagram",
                  "validation_comment",
                  "validation_reason"
                ]
              }
            }
          },
          "required": [
            "paper",
            "paper_id",
            "questions",
            "tier"
          ]
        }
      }
    },
    "required": [
      "board_title",
      "papers",
      "qualification",
      "series",
      "subject_id",
      "subject_title",
      "type"
    ]
  }
}

=== MWJones96/medly-backend-take-home-task/curriculum_data/aqaGCSEBio_exams.json
[
  {
    "board_title": "aqa",
    "qualification": "GCSE",
    "subject_title": "Biology",
    "subject_id": "aqaGCSEBio",
    "type": "Medly",
    "series": "Sept_Mock",
    "papers": [
      {
        "paper_id": "medlymockaqaGCSEBio_Sept_Mock1Higher",
        "tier": "Higher",
        "paper": "1",
        "questions": [
          {
            "question_number": 1,
            "question_stem": "A pharmaceutical company is developing a new antiviral drug, ‘Virostop’, to treat a new strain of influenza.\n\n**Table 1** below shows data about the number of potential drug compounds tested during the development process.",
            "question_stem_diagram": "\n\n**Table 1**\n\n| Stage of Development | Number of Compounds Entering Stage | Number of Compounds Failing Stage | Main Reason for Failure |\n|---|---|---|---|\n| Preclinical testing | 8000 | 7980 | High toxicity to animal cells |\n| Clinical trial - Phase 1 | 20 | 12 | Unacceptable side effects in healthy volunteers |\n| Clinical trial - Phase 2 | 8 | 5 | Drug was not effective at treating the virus |\n| Clinical trial - Phase 3 | 3 | 2 | Drug was less effective than existing treatments |",
            "items": [
              {
                "question_part": 1,
                "question_type": "long_answer",
                "question_text": "What is the main reason that compounds failed during the Phase 2 clinical trials?",
                "markmax": 1,
                "markscheme": "drug was not effective (at treating the virus)\nallow it did not work",
                "difficulty": 3,
                "lessonIDs": [
                  "aqaGCSEBio2.0.12",
                  "aqaGCSEBio2.0.13",
                  "aqaGCSEBio2.0.14"
                ],
                "questionID": "aqaGCSEBio_1_1_1_EBc0BgD11T"
              },
              {
                "question_part": 2,
                "question_type": "calculate",
                "question_text": "Calculate the percentage of compounds that entered preclinical testing and were successful. \n\nOne compound was successful. \n\nGive your answer to two significant figures. Show your working.",
                "markmax": 2,
                "markscheme": "$(1 \\div 8000) \\times 100$ (1)\n0.013 (%) (1)\nallow 0.0125 (%) for 1 mark",
                "difficulty": 5,
                "lessonIDs": [
                  "aqaGCSEBio0.2.7",
                  "aqaGCSEBio2.0.12",
                  "aqaGCSEBio2.0.14"
                ],
                "questionID": "aqaGCSEBio_1_1_2_UzkAhNy7ZM"
              },
              {
                "question_part": 3,
                "question_type": "long_answer",
                "question_text": "In clinical trials, some volunteer patients are given a placebo. \n\nDefine what is meant by a placebo.",
                "markmax": 1,
                "markscheme": "a substance / pill with no active drug / medicine in it\nallow a fake / dummy pill",
                "difficulty": 2,
                "lessonIDs": [
                  "aqaGCSEBio2.0.14"
                ],
                "questionID": "aqaGCSEBio_1_1_3_sDYbfk7txs"
              },
              {
                "question_part": 4,
                "question_type": "long_answer",
                "question_text": "Suggest one reason why it is important to use a placebo in drug trials.",
                "markmax": 1,
                "markscheme": "to act as a control / for comparison\nOR\nto check for the placebo effect / psychological effect\nOR\nto see if the drug has a greater effect than no treatment\nignore to make it a fair test",
                "difficulty": 4,
                "lessonIDs": [
                  "aqaGCSEBio2.0.14"
                ],
                "questionID": "aqaGCSEBio_1_1_4_z7ttK093HL"
              },
              {
                "question_part": 5,
                "question_type": "long_answer",
                "question_text": "Phase 3 trials are often 'double-blind'. \n\nDescribe what is meant by a double-blind trial.",
                "markmax": 2,
                "markscheme": "neither the doctors / scientists nor the patients know (who has the drug/placebo) (1)\n(this is) to prevent bias (1)",
                "difficulty": 5,
                "lessonIDs": [
                  "aqaGCSEBio2.0.12",
                  "aqaGCSEBio2.0.14"
                ],
                "questionID": "aqaGCSEBio_1_1_5_54QKJNfT5B"
              },
              {
                "question_part": 6,
                "question_type": "long_answer",
                "question_text": "A journalist wrote: ‘The high cost of new medicines is mainly due to the very high failure rate of potential drugs.’\n\nSuggest how information from **Table 1** supports this statement.",
                "markmax": 1,
                "markscheme": "Very large number / 7999 of compounds fail (for every 1 that succeeds)\nOR\nonly 1 out of 8000 compounds was successful",
                "difficulty": 6,
                "lessonIDs": [
                  "aqaGCSEBio2.0.12",
                  "aqaGCSEBio2.0.13",
                  "aqaGCSEBio2.0.14",
                  "aqaGCSEBio5.2.14"
                ],
                "questionID": "aqaGCSEBio_1_1_6_7AuUr0RWcx"
              }
            ],
            "validation_comment": "PASS",
            "validation_reason": "The question is syllabus-appropriate, with good ramping of cognitive demand for higher-tier.",
            "question_id": "aqaGCSEBio_1_1_jvJIpxZhci"
          },
          {
            "question_number": 2,
            "question_stem": "A professional free-diver performs a timed dive. Scientists record physiological data before the dive and immediately after the diver resurfaces.\n\n\n**Table 2** shows some of the data collected.\n\n\n**Table 2**\n\n\n| Parameter                               | Before Dive (at rest) | Immediately After Resurfacing |\n|-----------------------------------------|-----------------------:|------------------------------:|\n| Blood pH                                |                   7.4  |                           7.1 |\n| Muscle Glycogen concentration (arb. u.) |                    85  |                            45 |\n| Blood Lactate concentration (mmol/dm³)  |                   1.2  |                          14.2 |\n| Breathing Rate (breaths per minute)     |                    12  |                            48 |\n\n\n",
            "question_stem_diagram": null,
            "items": [
              {
                "question_part": 1,
                "question_type": "long_answer",
                "question_text": "Explain why the diver's breathing rate remains high for several minutes after resurfacing. Use information from **Table 2**.",
                "markmax": 3,
                "markscheme": "•(anaerobic respiration produces) lactic acid/lactate (1)\n\n•(extra) oxygen is needed to break down the lactic acid (1)\n\n•Repay oxygen debt (1)",
                "difficulty": 3,
                "lessonIDs": [
                  "aqaGCSEBio3.1.6",
                  "aqaGCSEBio3.1.7"
                ],
                "questionID": "aqaGCSEBio_1_2_1_CxYmNonmRy"
              },
              {
                "question_part": 2,
                "question_type": "calculate",
                "question_text": "Calculate the percentage decrease in the diver's muscle glycogen concentration. Show your working.",
                "markmax": 2,
                "markscheme": "(decrease =) 85 - 45 (= 40) (1)\n\n(40 / 85 x 100 =) 47.1 (%) (1)\n\nallow 47 (%)\nallow correct answer for 2 marks, even without working",
                "difficulty": 2,
                "lessonIDs": [
                  "aqaGCSEBio0.2.7",
                  "aqaGCSEBio3.1.9",
                  "aqaGCSEBio4.2.3",
                  "aqaGCSEBio3.1.7"
                ],
                "questionID": "aqaGCSEBio_1_2_2_CzConyRFZc"
              },
              {
                "question_part": 3,
                "question_type": "long_answer",
                "question_text": "Give two pieces of evidence from **Table 2** that suggest the diver's muscle cells respired anaerobically.",
                "markmax": 2,
                "markscheme": "Any two from:\n• blood lactate / lactic acid increases (from 1.2 to 14.2) (1)\n• muscle glycogen decreases (showing glucose has been used up for respiration) (1)\n• blood pH decreases / blood becomes more acidic (1)",
                "difficulty": 5,
                "lessonIDs": [
                  "aqaGCSEBio3.1.2",
                  "aqaGCSEBio3.1.4",
                  "aqaGCSEBio3.1.6",
                  "aqaGCSEBio3.1.7"
                ],
                "questionID": "aqaGCSEBio_1_2_3_0xW1CO63jH"
              },
              {
                "question_type": "long_answer",
                "question_text": "Lactic acid produced during the dive can cause muscle fatigue. Suggest one reason why the decrease in blood pH is dangerous for the diver.",
                "markmax": 1,
                "markscheme": "(low pH / high acidity) denatures enzymes (1)\n\nallow (this) slows down / stops metabolic reactions\nallow named examples of metabolic reactions",
                "lessonIDs": [
                  "aqaGCSEBio1.1.1",
                  "aqaGCSEBio4.0.0",
                  "aqaGCSEBio3.1.7",
                  "aqaGCSEBio1.1.2"
                ],
                "question_part": 4,
                "questionID": "aqaGCSEBio_1_2_4_NELiyfw35w"
              },
              {
                "question_type": "long_answer",
                "question_text": "What is the word equation for anaerobic respiration in muscle cells?",
                "markmax": 1,
                "markscheme": "glucose $\\rightarrow$ lactic acid (1)\n\nallow lactate\nignore (+ little energy)",
                "lessonIDs": [
                  "aqaGCSEBio3.1.4",
                  "aqaGCSEBio3.1.2",
                  "aqaGCSEBio3.1.7"
                ],
